name: Upload PHP Builds
run-name: Upload PHP builds for ${{ inputs.php-version }}
on:
  workflow_dispatch:
    inputs:
      php-version:
        description: 'PHP version to build'
        required: true
      url:
        description: 'Artifact URL'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Upload
        run: |
          curl \
          --request POST \
          --location https://downloads.php.net/api/php \
          --header 'Authorization: Bearer ${{ secrets.AUTH_TOKEN }}' \
          --data '{ "url": "${{ inputs.url }}", "token": "${{ secrets.TOKEN }}" }'
